config/routes.rb
Rails.application.routes.draw do
  resources :staffs
  resources :empmanages
  #get 'home/index'
  get 'home/about'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/empmanage.rb
class Empmanage < ApplicationRecord
end

app/models/staff.rb
class Staff < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/empmanages_controller.rb
class EmpmanagesController < ApplicationController
  before_action :set_empmanage, only: %i[ show edit update destroy ]

  # GET /empmanages or /empmanages.json
  def index
    @empmanages = Empmanage.all
  end

  # GET /empmanages/1 or /empmanages/1.json
  def show
  end

  # GET /empmanages/new
  def new
    @empmanage = Empmanage.new
  end

  # GET /empmanages/1/edit
  def edit
  end

  # POST /empmanages or /empmanages.json
  def create
    @empmanage = Empmanage.new(empmanage_params)

    respond_to do |format|
      if @empmanage.save
        format.html { redirect_to @empmanage, notice: "Empmanage was successfully created." }
        format.json { render :show, status: :created, location: @empmanage }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @empmanage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /empmanages/1 or /empmanages/1.json
  def update
    respond_to do |format|
      if @empmanage.update(empmanage_params)
        format.html { redirect_to @empmanage, notice: "Empmanage was successfully updated." }
        format.json { render :show, status: :ok, location: @empmanage }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @empmanage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /empmanages/1 or /empmanages/1.json
  def destroy
    @empmanage.destroy
    respond_to do |format|
      format.html { redirect_to empmanages_url, notice: "Empmanage was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_empmanage
      @empmanage = Empmanage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def empmanage_params
      params.require(:empmanage).permit(:first_name, :last_name, :age, :gender, :designation)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :set_staff, only: %i[ show edit update destroy ]

  # GET /staffs or /staffs.json
  def index
    @staffs = Staff.all
  end

  # GET /staffs/1 or /staffs/1.json
  def show
  end

  # GET /staffs/new
  def new
    @staff = Staff.new
  end

  # GET /staffs/1/edit
  def edit
  end

  # POST /staffs or /staffs.json
  def create
    @staff = Staff.new(staff_params)

    respond_to do |format|
      if @staff.save
        format.html { redirect_to @staff, notice: "Staff was successfully created." }
        format.json { render :show, status: :created, location: @staff }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /staffs/1 or /staffs/1.json
  def update
    respond_to do |format|
      if @staff.update(staff_params)
        format.html { redirect_to @staff, notice: "Staff was successfully updated." }
        format.json { render :show, status: :ok, location: @staff }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staffs/1 or /staffs/1.json
  def destroy
    @staff.destroy
    respond_to do |format|
      format.html { redirect_to staffs_url, notice: "Staff was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staff
      @staff = Staff.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def staff_params
      params.require(:staff).permit(:first_name, :last_name, :age, :gender, :designation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/empmanages_helper.rb
module EmpmanagesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  	<%= link_to 'Employee Management', root_path, class:"navbar-brand" %>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
       

          <li class="nav-item">
          <%= link_to "Employees",staffs_path,class:"nav-link"%>
          <li class="nav-item">
          <%= link_to "Add an Employee",new_staff_path,class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "About us",home_about_path,class:"nav-link"%>
      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<br>
<h1>About us</h1><br>
<body>
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">Surya Ganesan</h5>
    <p class="card-text">If you have any queries you can contact me via twitter</p>
    <a href="https://www.twitter.com/0xSurya" class="btn btn-outline-info stretched-link">Twitter</a>
  </div>
</div>
</body>

app/views/home/index.html.erb
<br>
<h1><center>Employee Management Console!</center></h1>
<br>
<br>

          <center><%= link_to "Admin Login",staffs_path,class:"btn btn-outline-success"%></center>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
<footer>
  <p>Authentication page goes here(soon)...</p>
</footer>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice  %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <title>Employee</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <title>Hello, world!</title>
  </head>
  <body>
    <%= render 'home/header'%>
    <div class="container">

<% if notice %>
<%= render 'layouts/alerts' %>
<% end %>
    
    <%= yield %>
  </div>


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/staffs/_form.html.erb
<%= form_with(model: staff) do |form| %>
  <% if staff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(staff.errors.count, "error") %> prohibited this staff from being saved:</h2>

      <ul>
        <% staff.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group ">
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name" %>
  </div>
<br>
  <div class="field form-group">
     <%= form.text_field :last_name , class:"form-control", placeholder:"Last Name" %>
  </div>
<br>
  <div class="field form-group">
     <%= form.number_field :age ,class:"form-control", placeholder:"Age" %>
  </div>
<br>

  <div class="field form-group">
     <%= form.text_field :gender,class:"form-control",placeholder:"Gender" %>
  </div>
<br/>

  <div class="field form-group">
     <%= form.text_field :designation ,class:"form-control" , placeholder:"Designation" %>
  </div>
<br>

  <div class="actions">
    <input type="submit" name="commit" value="Create Employee" class="btn btn-success" data-disable-with="Create Staff">
  </div>

<% end %>

app/views/staffs/edit.html.erb
<h1>Edit Employee Details</h1>

<%= render 'form', staff: @staff %>
<br>

<%= link_to 'Show', @staff , class:"btn btn-outline-info" %> 
<%= link_to 'Back', staffs_path , class:"btn btn-outline-dark" %>

app/views/staffs/index.html.erb
<h1>Employee List</h1>

<table class="table table table table-bordered table-hover table-striped">
  <thead class="table-dark">
      <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Age</th>
      <th>Gender</th>
      <th>Designation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @staffs.each do |staff| %>
      <tr>
        <td><%= staff.first_name %></td>
        <td><%= staff.last_name %></td>
        <td><%= staff.age %></td>
        <td><%= staff.gender %></td>
        <td><%= staff.designation %></td>
        <td><%= link_to 'Show', staff, class:"btn btn-outline-primary" %></td>
        <td><%= link_to 'Edit', edit_staff_path(staff), class:"btn btn-outline-info" %></td>
        <td><%= link_to 'Delete',staff, class:"btn btn-outline-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_staff_path, class:"btn btn-success"  %>

app/views/staffs/new.html.erb
<h1>Add New Employee</h>
	<br/>

<%= render 'form', staff: @staff %>

<%= link_to 'Back', staffs_path , class:"btn btn-primary" %>

app/views/staffs/show.html.erb
<div class="jumbotron">
  <h1 class="display-4">  <%= @staff.first_name %>
      <%= @staff.last_name %>

</h1>
  <p class="lead">  <%= @staff.age %> |   <%= @staff.gender %> |   <%= @staff.designation %>
</p>
  <hr class="my-4">
  <%= link_to 'Edit', edit_staff_path(@staff), class:"btn btn-outline-info" %>        
<%= link_to 'Back', staffs_path, class:"btn btn-dark" %>
</div>